### ISSUE TITLE
Required argument for option "--text" is missing

### ISSUE THREAD

**Issue by maelga** [sebastianbergmann/phpcov#103]
My workflow on Gitlab CI has been relying on the --text option without any argument to pick merged code coverage and spin it into a badge for the repo.
```  
script:
    - php phpcov.phar merge CodeCoverage --text
```

I am now getting this error as a filename is now required:
```Required argument for option "--text" is missing```

and I understand that --text option no longer falls back to `php://stdout` according to this comment in other issue:

> While cleaning up phpcov, I decided to not fall back to `php://stdout` anymore when --text is used without an argument.
[https://github.com/sebastianbergmann/php-code-coverage/issues/792#issuecomment-672567394](url)

So what is the option to get  `php://stdout` output?

**Comment by sebastianbergmann** [comment]
You can use `--text php://stdout`.
