### ISSUE TITLE
Docker official image 

### ISSUE THREAD

**Issue by Legion112** [sebastianbergmann/phpcov#119]
Would be nice to have supported docker image here.
For each version. 
Ideally I could create a pull request with Dockerfile and GitHubAction job to build it on each release. 

https://hub.docker.com/search?q=phpcov

**Comment by sebastianbergmann** [comment]
Feel free to do that on your own and outside of this project.

**Comment by Legion112** [comment]
What do you think about mentioning the usage of my image in the readme section? 
```shell
docker run --rm -w /app/ -v $(pwd):/app/ fearofcode/phpcov:6.0.1  merge --xml .phpunit.coverage.xml  .phpunit.coverage.php/
```
That would benefit the others to quickly set up CI
