### ISSUE TITLE
HTML Coverage Reports for Patch-Coverage

### ISSUE THREAD

**Issue by Jackson-H-Code** [sebastianbergmann/phpcov#133]
**Question**
When running phpcov patch-coverage, the only output option is through the command line, or into a .txt file. Is it currently possible to generate an html representation of this coverage option, or will there be an option to do this in the future?

For example, 
`$ phpcov patch-coverage --path-prefix /path/to/project --html /path/to/htmlReport /tmp/coverage.cov /tmp/patch.txt`

Thanks in advance.

**Comment by sebastianbergmann** [comment]
This is outside the scope of this project.
