### ISSUE TITLE
Support for `11.0.0` version of `phpunit/php-code-coverage`

### ISSUE THREAD

**Issue by tarlepp** [sebastianbergmann/phpcov#136]
Current version of `phpcov` cannot be used with `phpunit/php-code-coverage` version `11.0.0`.

**Comment by sebastianbergmann** [comment]
There is also currently no (released) version of PHPUnit that can be used with the `11.0.0` version of `phpunit/php-code-coverage`.

**Comment by tarlepp** [comment]
Hmm, imho this issue is still open - you really didn't give the answer why that support is not there.

If you have knowledge when other libraries would have that support for `11.0.0` version - I really think that would help people.
