### ISSUE TITLE
I get an error message:zend_mm_heap corrupted

### ISSUE THREAD

**Issue by guo2312668** [sebastianbergmann/phpcov#140]
phpcov:7.0.2
php:7.3.31
phpunit/php-code-coverage:8.0

When I execute phpcov, I get an error message:"zend_mm_heap corrupted"

If I disable the php extension php_screw_plus, it can execute normally

But my project needs to use php_screw_plus, how should I solve it? Thanks

**Comment by sebastianbergmann** [comment]
You have found a problem in the PHP runtime or in an extension for it. This is outside the scope of this issue tracker.
