### ISSUE TITLE
Bump the phar for PHP 8.4

### ISSUE THREAD

**Issue by mariusjp** [sebastianbergmann/phpcov#144]
Looking at this issue: https://github.com/sebastianbergmann/php-code-coverage/issues/1043 your library is ready for PHP 8.4, but this project that "produces" the phar (I'm not that familiar with phar) seems to download an older version because I'm getting an error on PHP Parser:

```
PHP Fatal error:  Uncaught PhpParser\Error: Syntax error, unexpected T_OBJECT_OPERATOR on line 98 in phar:///var/www/html/bin/phpcov.phar/nikic/PhpParser/ParserAbstract.php:359
```

To clarify further, I started getting this error the moment I switched to PHP 8.4, on 8.3 everything was working just fine

**Comment by sebastianbergmann** [comment]
Should be fixed in phpcov 10.0.1.
