### ISSUE TITLE
Merging .cov files ignores their filter settings

### ISSUE THREAD

**Issue by fluxcorenz** [sebastianbergmann/phpcov#18]
Each .cov file has its own filters - whitelists, blacklists, etc. When performing a phpcov merge operation, these filters are ignored, and a default filter is used. 

In particular, this results in any processUncoveredFilesFromWhitelist setting being ignored. The filenames are all in the .cov's filter whitelist, but the merge operation ignores them.

Possibly there could be filter options made available to the command line, which would allow filtering the complete set, or perhaps the filter within the file being merged could be used to check against, instead of the default (see PHP_CodeCoverage::merge  line which reads:
```
 if (!$this->filter->isFiltered($file)) {
```
--could potentially check $that->filter()->isFiltered($file) in this instance instead?)

Or some kind of pre-merge on the filters could happen.

I wouldn't be adverse to implementing something if a preferred design was decided upon.

**Comment by svycka** [comment]
I can confirm this .cov has all files in the filter but after merge generated html report missed them.

**Comment by sebastianbergmann** [comment]
Using `$that->filter()->isFiltered($file)` makes sense to me. Can you send a pull request?

**Comment by sebastianbergmann** [comment]
https://github.com/sebastianbergmann/php-code-coverage/pull/314 was reverted.

**Comment by foozee** [comment]
merging whitelists and blacklists after you have already passed Line 352 where the check `if (!$this->filter->isFiltered($file))` has already failed doesn't solve the problem ... the issue is still reproducible.. however, moving the merges before the `foreach` on line 350 seems to be working well!
