### ISSUE TITLE
Can phpcov with the 'execute' option handle arguments to the script?

### ISSUE THREAD

**Issue by tchaffee** [sebastianbergmann/phpcov#26]
I have a command that I normally run like this:

```
php console rabbitmq:consumer -m 50 -w search_events -e=prod
```

I would like to execute that script and pass it arguments, using `phpcov`. Is that possible? From my own experiments it seems like `phpcov` will just reject the additional arguments as not valid, but maybe I am missing something.

**Comment by sebastianbergmann** [comment]
You are correct, this is not possible. I do not know how to implement this and would gladly accept a pull request that implements this.

Sorry for taking so long to respond.
