### ISSUE TITLE
Support PHPUnit 5

### ISSUE THREAD

**Issue by ruudk** [sebastianbergmann/phpcov#38]
Currently, PHPUnit 5 is not supported.

**Comment by sebastianbergmann** [comment]
This is a separate tool. What do you mean by "PHPUnit 5 is not supported"?

**Comment by ruudk** [comment]
I have PHPUnit 5 installed and I get the following error when running 

```
composer require phpunit/phpcov
  Problem 1
    - phpunit/phpcov 2.0.1 requires phpunit/phpunit ~4.1 -> no matching package found.
    - phpunit/phpcov 2.0.0 requires phpunit/phpunit ~4.0 -> no matching package found.
    - Installation request for phpunit/phpcov ^2.0 -> satisfiable by phpunit/phpcov[2.0.0, 2.0.1].
```

**Comment by sebastianbergmann** [comment]
Ah, you are pulling in both PHPUnit and PHPCOV as dependencies via Composer. Did not think about this because I almost never use Composer to install PHPUnit and never to install PHPCOV.

**Comment by ruudk** [comment]
Yep, Sorry for the confusion :)

**Comment by sebastianbergmann** [comment]
No worries, I'll look into it.

**Comment by sebastianbergmann** [comment]
Would changing
```
"phpunit/phpunit": "~4.1",
```
to
```
"phpunit/phpunit": "~4|~5",
```
in `composer.json` already fix this?

**Comment by ruudk** [comment]
Yep, I think so :)

**Comment by remicollet** [comment]
Still blocked by  "phpunit/php-code-coverage": "~2.0" (as PHPUnit 5 requires ~3.0)

**Comment by remicollet** [comment]
And some tests still use "setBlacklistedFiles" while phpunit/phpcov 3.0 only have withlist...

**Comment by ruudk** [comment]
The problem is indeed `"phpunit/php-code-coverage": "~2.0"`

Could you please bump it to ~3.0 and create a new major release for phpcov? I can create a PR if that helps.
