### ISSUE TITLE
phpcov.phar InvalidArgumentException Template file could not be loaded. when merging coverage to html

### ISSUE THREAD

**Issue by fatalcoder** [sebastianbergmann/phpcov#40]
With "bare" code from repo this command works fine, but for phar don't.

```
bin/phpcov merge --html="coverage" build/coverage
```

I get exception

```
[InvalidArgumentException]          
  Template file could not be loaded.
```

I am using phpcov 2.0.1 but when I builded new phar from master issue still exists

**Comment by radepal** [comment]
I have same problem 
I need to merge results from many smaller cov files and I cant generate this html report with same error

**Comment by fatalcoder** [comment]
Here is pull request to fix this issue
https://github.com/sebastianbergmann/phpcov/pull/41

**Comment by stubbetje** [comment]
Was facing the same issue and the solution proposed by @fatalcoder fixed it :+1:
