### ISSUE TITLE
Verify coverage

### ISSUE THREAD

**Issue by seggen-ibuildings** [sebastianbergmann/phpcov#50]
I had an idea, how about adding a command that verifies code coverage? You could read an .cov file, extract the coverage percentage, compare it to a given target and then exit with either 0 or 1.

If I had the time I'd build it myself :) Maybe on the AmsterdamPHP/DPC Codenight next month...

**Comment by sebastianbergmann** [comment]
Not going to add this as this should be done through a continuous integration server.

**Comment by seggen-ibuildings** [comment]
That was my initial thought as well, but this is different for [Yenkins](https://wiki.jenkins-ci.org/display/JENKINS/Clover+PHP+Plugin) and [Bamboo](https://confluence.atlassian.com/bamboo/using-bamboo-with-clover-289277349.html), and I'm not even sure how to do it in [Travis](https://ocramius.github.io/blog/automated-code-coverage-check-for-github-pull-requests-with-travis/). (If you use Travis, you apparently want to use some SaaS for code coverage reporting as well.)

And on top of that, what if you want to test-run the CI build on your checkout?

Anyway, I wouldn't mind writing it myself, but I gather that you think it I should write it as a different tool. Am I right?

**Comment by sebastianbergmann** [comment]
Feel free to send a pull request.
