### ISSUE TITLE
Compatibility with phpunit/php-code-coverage 4

### ISSUE THREAD

**Issue by remicollet** [sebastianbergmann/phpcov#52]
I saw some work already done in master.

Any ETA for a new Release ?
(blocker to update to 5.4 in Fedora, with https://github.com/mnapoli/phpunit-easymock/issues/4)

**Comment by sebastianbergmann** [comment]
Some time today.

**Comment by remicollet** [comment]
Thanks :)

**Comment by sebastianbergmann** [comment]
Interrupted breakfast, just for you :)

**Comment by remicollet** [comment]
But breakfast is sacred!
