### ISSUE TITLE
Text coverage broken under phpcov 3.0.1

### ISSUE THREAD

**Issue by lukewaite** [sebastianbergmann/phpcov#54]
Hello,

Are you able to apply the patch which fixed text coverage in `3.1.0` to the `3.0` branch?
https://github.com/sebastianbergmann/phpcov/commit/d1cac8424ac0483fdc80cf339d6cc4c30e73bb21

I'm not currently able to update to 3.1.0. It's dependency on php-code-coverage 4.x is causing me a bit of headaches on non-namespaced files in laravel, namely the routes file. I'm working to solve that issue, but in the meantime if you'd be able to backport this fix to `3.0` it would be greatly appreciated.

I can confirm that manually applying the commit fixes the issues I am experiencing with phpcov not outputting anything for text coverage.

Thanks!

**Comment by Webysther** [comment]
@lukewaite you can check is working?

**Comment by lukewaite** [comment]
Unless a new 3.0.x tag is released, which will not happen, this remains an open issue under 3.0.1.

It is fixed under 3.1, however that version (3.1) requires updating from 3.x to 4.x on `php-code-coverage` and is/was giving me trouble.

**Comment by sebastianbergmann** [comment]
There will be no more 3.0 releases.
