### ISSUE TITLE
cannot merge multiple .cov files 

### ISSUE THREAD

**Issue by i928** [sebastianbergmann/phpcov#63]
I run merge command
 ./phpcov merge c:/inetpub/wwwroot/ccn/reports/coverage --clover tmp/clover.xml
and get following error.
Generating code coverage report in Clover XML format ... done
Failed to merge: C:\inetpub\wwwroot\ccn\reports\coverage\590f7c0fe27b2.cov
Failed to merge: C:\inetpub\wwwroot\ccn\reports\coverage\590f7cbc2f7e5.cov
attach these 2 files.
[590f7cbc2f7e5.txt](https://github.com/sebastianbergmann/phpcov/files/981961/590f7cbc2f7e5.txt)
[590f7c0fe27b2.txt](https://github.com/sebastianbergmann/phpcov/files/981963/590f7c0fe27b2.txt)

**Comment by marcelopm** [comment]
I'm not sure but, according to the docs, I think the *.cov files need to be in php format: --coverage-php=${filename}.cov

**Comment by sebastianbergmann** [comment]
Yes, they need to be in PHP format.
