### ISSUE TITLE
Add commande line option to define low and high bound

### ISSUE THREAD

**Issue by psa-jforestier** [sebastianbergmann/phpcov#66]
The phpcov command line should implement options to define the lowUpperBound and highLowerBound boundaries. This settings are not accessible by the command line (only the PHPUnit interface can modify them).
I propose to add command line options "--lowupperbound" and "--highlowerbound" . Theses options are used by the HTML report to classify the coverage, but the default values (50% and 90%) cant be changed by the command line interface.
Thanks.

**Comment by psa-jforestier** [comment]
Please have a look at this PR to solve this feature request: https://github.com/sebastianbergmann/phpcov/pull/67

**Comment by sebastianbergmann** [comment]
I would rather not solve this through adding new commandline arguments but by reading the configuration from a `phpunit.xml` configuration file, if possible.

**Comment by psa-jforestier** [comment]
I agree with this remark. I'm working on it.

**Comment by psa-jforestier** [comment]
hmm seems to be difficult to get this params from a phpunit.xml file, because this XML do not have element for this settings. They are attributes of the <logging><log type="coverage-html"> element, so this two settings are members of the <log> sets, but they are not global to the XML file.
I dont know if the phpunit.xml schema is extensible to cover this feature.

**Comment by sebastianbergmann** [comment]
I do not understand why you want to change/extend the `phpunit.xml` schema. Simply take the values of the attributes from the HTML code coverage element.

**Comment by psa-jforestier** [comment]
Please have a look at the new PR https://github.com/sebastianbergmann/phpcov/pull/68 .
It use the `<logging/log type="coverage-html">` element and the the two existing attributes, as you suggested it. I was not confident with this, because to be _clean_ I should also implement the "target" attribute (as the folder to generate the report), but it was not my goal at the begining.

**Comment by psa-jforestier** [comment]
Hi Sebastian.
Can you please have a look at PR #68 and let me know if you can merge it ? (i work with the 3.1 version so the PR is dedicated to this version).
