### ISSUE TITLE
Missing "--configuration" option for "merge" command

### ISSUE THREAD

**Issue by matthiasnoback** [sebastianbergmann/phpcov#78]
At this moment, the `merge` command has no `configuration` option (`execute` does). I thought about submitting it as a PR (shouldn't be a difficult one), but maybe I'm missing a reason for not doing so. Please let me know if it's a good idea to work on this :)

**Comment by sebastianbergmann** [comment]
I don't recall a reason for not having a `configuration` option for `merge`.

**Comment by matthiasnoback** [comment]
I looked at this, and though the change itself is really small (there's already a method `handleConfiguration()` in the parent `BaseCommand`), it has no useful effect because `CodeCoverage::merge()` [merges whitelisted files](https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/CodeCoverage.php#L370) from both `CodeCoverage` instances. This is nice, since merging would be the equivalent of a union operation, but I was looking for a way to apply the original filtering to the merged `CodeCoverage` object.

I guess the easiest solution would be to add some "flag" parameter to `merge()` (`bool $preserveFilterConfiguration`). When `true`, this would basically skip the `array_merge()` call.

What are your thoughts on this?
