### ISSUE TITLE
Which version will work with phpunit 6.5.12?

### ISSUE THREAD

**Issue by dingo-d** [sebastianbergmann/phpcov#81]
I'm trying to set up phpcov to work with phpunit 6.5.12 but, no matter which version I try, it seems to fail. 

I'm limited to 6.5 because I'm running unit and integration tests on a WordPress plugin, and apparently WordPress only works with v 6.5 :/

**Comment by sebastianbergmann** [comment]
PHPUnit 6.5 is no longer supported. Please open a new ticket in case this still applies to a supported version of PHPUnit.
