### ISSUE TITLE
phpcov silently failing

### ISSUE THREAD

**Issue by asra-baig** [sebastianbergmann/phpcov#83]
I'm running this:
php -d memory_limit=-1 vendor/bin/phpcov merge ~/coverage --html ~/coverage_merge

And getting the following output:

```
phpcov 3.1.0 by Sebastian Bergmann.

Killed
```

The ~/coverage folder has these 16 files generated by phpunit with --coverage-php option:
coverage_report_0.cov  coverage_report_10.cov  coverage_report_12.cov  coverage_report_14.cov  coverage_report_2.cov  coverage_report_4.cov  coverage_report_6.cov  coverage_report_8.cov
coverage_report_1.cov  coverage_report_11.cov  coverage_report_13.cov  coverage_report_15.cov  coverage_report_3.cov  coverage_report_5.cov  coverage_report_7.cov  coverage_report_9.cov

**Comment by asra-baig** [comment]
If there is only one file in coverage folder, I see this output:
```
phpcov 3.1.0 by Sebastian Bergmann.


Generating code coverage report in HTML format ...
```
followed by html report generation.

**Comment by asra-baig** [comment]
Some times I'm seeing this:

$ #!/bin/bash -eo pipefail
source ./.circleci/lib/functions.sh && run_phpunit_tests_coverage_merge
phpcov 3.1.0 by Sebastian Bergmann.

./.circleci/lib/functions.sh: line 175:   557 Killed                  php -d memory_limit=-1 vendor/bin/phpcov merge ~/coverage --html ~/coverage_merge
PHPUnit coverage merge failed
Exited with code 1

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.
