### ISSUE TITLE
merging coverage files generated with codeception

### ISSUE THREAD

**Issue by jcheron** [sebastianbergmann/phpcov#87]
## Problem:
I use codeception for acceptance (with Selenium) and local unit tests.
I want to merge remote coverage with local.
The 2 generated reports make references to the same files (identical paths and namespaces), however, codeception does not merge them.

So I'm trying to use phpcov...

I use the `--coverage` option to produce serialized format files
```bash
codecept run --coverage
```
The 2 generated files are:
  - `coverage.serialized` in the `_output` local folder
  - `codecoverage.serialized`in the `_output/c3tmp` remote folder on the web server
I copy the remote file in the same folder (`tests/_output`) that the local and execute:
```bash
./vendor/bin/phpcov merge tests/_output/ --clover tests/_output/coverage-all.xml
```
Console output:
```
phpcov 5.0.0 by Sebastian Bergmann.
Generating code coverage report in Clover XML format ... done
```
No error, but the generated file is empty:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<coverage generated="1548805986">
  <project timestamp="1548805986">
    <metrics files="0" loc="0" ncloc="0" classes="0" methods="0" coveredmethods="0" conditionals="0" coveredconditionals="0" statements="0" coveredstatements="0" elements="0" coveredelements="0"/>
  </project>
</coverage>
```
phpcov is it compatible with codeception and the `serialized` format as some say? see https://github.com/Codeception/Codeception/issues/3245#issuecomment-228812484

## configuration
* phpcov version: 5.0.0
* Codeception version: 2.5.2
* PHPUnit: 7.5.2
* PHP Version: 7.2.13
* Operating System: Debian ? (Scrutinizer-ci)
* Installation type: Composer

**Comment by ahocquard** [comment]
Hello,

I didn't use codeception at all, so maybe my comment is not relevant.
Did you configure a whitelist somewhere?

If there is nothing configured as whitelist, everything will be filtered. 
For example, with phpunit, you have to configure a whitelist this way:

```
Hello,

Did you configured the phpunit.xml with a  whitelist?
I had the same problem, and after investigation, the files `.cov` had no data due to this missing configuration.

https://phpunit.readthedocs.io/en/7.4/code-coverage-analysis.html#whitelisting-files

```
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">your_directory/</directory>
        </whitelist>
    </filter>
```

https://phpunit.readthedocs.io/en/7.4/code-coverage-analysis.html#whitelisting-files

**Comment by jcheron** [comment]
There is also a whitelist with codeception:
in `codeception.yml` file:
```yml
coverage:
    include:
        - directoryToInclude/
```
but the problem was elsewhere.
I found the solution, see https://github.com/Codeception/Codeception/issues/5368#issuecomment-460998252

Thank you for your answer
