### ISSUE TITLE
Incorrect line percentage

### ISSUE THREAD

**Issue by thewholelifetolearn** [sebastianbergmann/phpcov#89]
phpcov gives a 100% coverage for a method but not all are been tested. As it can be seen on the following screenshot, there are lines marked in red but the summary gives 100% covered.

Sorry for the big screenshot, but it is the best way to understand the issue.
![image](https://user-images.githubusercontent.com/823564/55480359-6a11bb80-5620-11e9-8036-f67eda7e16b4.png)

**Comment by sebastianbergmann** [comment]
Is this a php-code-coverage issue or an issue with phpcov?

**Comment by thewholelifetolearn** [comment]
I suppose that it comes from phpcov. It is phpcov that comes out with the statistics. The PHP coverage file created by PHPUnit seems correct. The lines marked as red are indeed not tested.  
For me, the issue comes from phpcov. How can I verify that?

**Comment by sebastianbergmann** [comment]
phpcov is merely a CLI frontend for the php-code-coverage library. Do you get the same output if you only use PHPUnit and not phpcov?

**Comment by thewholelifetolearn** [comment]
It seems that it comes from phpcov. PHPUnit gives a better result:

![image](https://user-images.githubusercontent.com/823564/55488442-65550380-5630-11e9-9772-29073ef1b15b.png)

```
Generated by php-code-coverage 7.0.3 using PHP 7.3.3 with Xdebug 2.7.0 and PHPUnit 8.0.6 at Wed Apr 3 16:46:24 CEST 2019.
```

**Comment by thewholelifetolearn** [comment]
But as I mentioned in issue #88 , the calculation method are different.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by thewholelifetolearn** [comment]
I'm at the moment in holidays. I will try to submit a test case before end of May.

**Comment by thewholelifetolearn** [comment]
I'm sorry i didn't propose a test case yet. I will propose one this month. I should have more spare time to do that.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
