### ISSUE TITLE
Different line coverage report result

### ISSUE THREAD

**Issue by lin-naing** [sebastianbergmann/phpcov#97]
Thank you PHPCOV.
It is good tool to merge from separated coverage report results to one.
I am merging of from three PHPUnit coverage results to one result by PHPCov.
Some line coverage reports are different. 

[PHPCov]
![PHPCov](https://user-images.githubusercontent.com/29984253/78878843-fe152f00-7a8d-11ea-8ee8-3eab8f2e4c28.PNG)

[PHPUnit]
![PHPUnit](https://user-images.githubusercontent.com/29984253/78878846-ffdef280-7a8d-11ea-8921-62e892798989.PNG)

Thank you.

**Comment by fabioginzel** [comment]
Any news?
